name: dart_mapper_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.4
  dart_mapper: 0.0.1
  built_value: ^8.9.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.5.7
  dart_mapper_generator: 0.0.1
  built_value_generator: ^8.9.2
  json_serializable: ^6.9.0

dependency_overrides:
  dart_mapper:
    path: ../packages/dart_mapper
  dart_mapper_generator:
    path: ../packages/dart_mapper_generator
