name: dart_mapper_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.4
  dart_mapper: any
  built_value: ^8.9.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^3.0.0
  dart_mapper_generator: any
  built_value_generator: ^8.9.2
  json_serializable: ^6.9.0
