// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'enum_mapper.dart';

// **************************************************************************
// DartMapperGenerator
// **************************************************************************

/// This class is a generated implementation of the abstract class EnumMapper.
/// Generated by DartMapperGenerator in date 2026-05-18 13:17:41.117270.
class EnumMapperImpl extends EnumMapper {
  EnumMapperImpl();

  @override
  EnumTarget toTarget(EnumSource source) {
    return switch (source) {
      EnumSource.element1 => EnumTarget.element1,
      EnumSource.element2 => EnumTarget.element2,
      EnumSource.element41 => EnumTarget.element41,
// ignore:unreachable_switch_case
      _ => throw ArgumentError('Unknown value for enum EnumTarget: {$source}'),
    };
  }

  @override
  UnbalancedEnumTarget toTargetCustom(EnumSource source) {
    return switch (source) {
      EnumSource.element1 => UnbalancedEnumTarget.element1,
      EnumSource.element2 => UnbalancedEnumTarget.element2,
      EnumSource.element41 => UnbalancedEnumTarget.element14,
// ignore:unreachable_switch_case
      _ => throw ArgumentError(
          'Unknown value for enum UnbalancedEnumTarget: {$source}'),
    };
  }

  @override
  EnumTarget toTargetWithSourceString(String source) {
    return switch (source) {
      'element1' => EnumTarget.element1,
      'element2' => EnumTarget.element2,
      'element41' => EnumTarget.element41,
// ignore:unreachable_switch_case
      _ => throw ArgumentError('Unknown value for enum EnumTarget: {$source}'),
    };
  }

  @override
  String toStringTargetWithEnumSource(EnumSource source) {
    return switch (source) {
      EnumSource.element1 => 'element1',
      EnumSource.element2 => 'element2',
      EnumSource.element41 => 'element41',
// ignore:unreachable_switch_case
      _ => throw ArgumentError('Unknown value for enum String: {$source}'),
    };
  }

  @override
  UnbalancedEnumTarget toTargetWithSourceInt(int source) {
    return switch (source) {
      1 => UnbalancedEnumTarget.element1,
      2 => UnbalancedEnumTarget.element2,
      14 => UnbalancedEnumTarget.element14,
// ignore:unreachable_switch_case
      _ => throw ArgumentError(
          'Unknown value for enum UnbalancedEnumTarget: {$source}'),
    };
  }

  @override
  UnbalancedEnumTarget? toNullableTargetWithSourceInt(int source) {
    return switch (source) {
      1 => UnbalancedEnumTarget.element1,
      2 => UnbalancedEnumTarget.element2,
      14 => UnbalancedEnumTarget.element14,
// ignore:unreachable_switch_case
      _ => null,
    };
  }

  @override
  int toIntTargetWithEnumSource(EnumSource source) {
    return switch (source) {
      EnumSource.element1 => int.parse('1'),
      EnumSource.element2 => int.parse('2'),
      EnumSource.element41 => int.parse('41'),
// ignore:unreachable_switch_case
      _ => throw ArgumentError('Unknown value for enum int: {$source}'),
    };
  }

  @override
  EnumTarget toTargetWithNullableSource([EnumSource? source]) {
    return switch (source) {
      null =>
        throw ArgumentError.notNull('The argument $source must not be null.'),
      EnumSource.element1 => EnumTarget.element1,
      EnumSource.element2 => EnumTarget.element2,
      EnumSource.element41 => EnumTarget.element41,
// ignore:unreachable_switch_case
      _ => throw ArgumentError('Unknown value for enum EnumTarget: {$source}'),
    };
  }

  @override
  EnumTarget? toTargetNullable(EnumSource source) {
    return switch (source) {
      EnumSource.element1 => EnumTarget.element1,
      EnumSource.element2 => EnumTarget.element2,
      EnumSource.element41 => EnumTarget.element41,
// ignore:unreachable_switch_case
      _ => null,
    };
  }

  @override
  EnumTarget? toTargetNullableBoth([EnumSource? source]) {
    return switch (source) {
      null => null,
      EnumSource.element1 => EnumTarget.element1,
      EnumSource.element2 => EnumTarget.element2,
      EnumSource.element41 => EnumTarget.element41,
// ignore:unreachable_switch_case
      _ => null,
    };
  }

  @override
  EnumTarget toTargetFromStringAutoPopulated(String source) {
    return switch (source) {
      'element1' => EnumTarget.element1,
      'element2' => EnumTarget.element2,
      'element41' => EnumTarget.element41,
// ignore:unreachable_switch_case
      _ => throw ArgumentError('Unknown value for enum EnumTarget: {$source}'),
    };
  }
}

/// This class is a generated implementation of the abstract class AnyRemainingEnumMapper.
/// Generated by DartMapperGenerator in date 2026-05-18 13:17:41.119016.
class AnyRemainingEnumMapperImpl extends AnyRemainingEnumMapper {
  AnyRemainingEnumMapperImpl();

  @override
  PrimaryTargetColor convert(ExtendedSourceColor source) {
    return switch (source) {
      ExtendedSourceColor.red => PrimaryTargetColor.red,
      ExtendedSourceColor.green => PrimaryTargetColor.green,
      ExtendedSourceColor.blue => PrimaryTargetColor.blue,
// ignore:unreachable_switch_case
      _ => PrimaryTargetColor.blue,
    };
  }
}

/// This class is a generated implementation of the abstract class AnyUnmappedEnumMapper.
/// Generated by DartMapperGenerator in date 2026-05-18 13:17:41.119383.
class AnyUnmappedEnumMapperImpl extends AnyUnmappedEnumMapper {
  AnyUnmappedEnumMapperImpl();

  @override
  PrimaryTargetColor? convert(ExtendedSourceColor source) {
    return switch (source) {
      ExtendedSourceColor.red => PrimaryTargetColor.red,
      ExtendedSourceColor.green => PrimaryTargetColor.green,
      ExtendedSourceColor.blue => PrimaryTargetColor.blue,
// ignore:unreachable_switch_case
      _ => null,
    };
  }
}

/// This class is a generated implementation of the abstract class NullValueSourceEnumMapper.
/// Generated by DartMapperGenerator in date 2026-05-18 13:17:41.119771.
class NullValueSourceEnumMapperImpl extends NullValueSourceEnumMapper {
  NullValueSourceEnumMapperImpl();

  @override
  PrimaryTargetColor convertNullable([ExtendedSourceColor? source]) {
    return switch (source) {
      null => PrimaryTargetColor.red,
      ExtendedSourceColor.red => PrimaryTargetColor.red,
      ExtendedSourceColor.green => PrimaryTargetColor.green,
      ExtendedSourceColor.blue => PrimaryTargetColor.blue,
// ignore:unreachable_switch_case
      _ => PrimaryTargetColor.blue,
    };
  }
}
