/*
 * Copyright (c) 2025 MyLittleSuite
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'package:dart_mapper/dart_mapper.dart';
import 'package:dart_mapper_example/subclass_mapping/models.dart';

part 'mapper.g.dart';

@Mapper()
abstract class MediaMapper {
  // The @SubclassMapping annotations declare which concrete types to dispatch.
  // The generator will produce:
  //
  //   @override
  //   MediaContentDto toDto(MediaContent source) {
  //     return switch (source) {
  //       Article article => toArticleDto(article),
  //       Video video => toVideoDto(video),
  //       _ => throw ArgumentError('Unexpected subtype: ${source.runtimeType}'),
  //     };
  //   }
  //
  // The wildcard is present because MediaContent is NOT sealed.
  @SubclassMapping(source: Article, target: ArticleDto)
  @SubclassMapping(source: Video, target: VideoDto)

  /// Dispatch method — body generated by dart_mapper based on @SubclassMapping.
  MediaContentDto toDto(MediaContent source);

  /// Delegate methods called by the generated dispatch.
  ArticleDto toArticleDto(Article source);
  VideoDto toVideoDto(Video source);
}
