name: Setup Flutter Environment and Get Dependencies

runs:
  using: "composite"
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Get dart dependencies
      shell: bash
      run: dart pub get
