name: dart_mapper
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/MyLittleSuite/dart_mapper.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
