name: dart_mapper
description: The dart mapper annotations.
version: 0.5.0
repository: https://github.com/MyLittleSuite/dart_mapper.git
issue_tracker: https://github.com/MyLittleSuite/dart_mapper/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.1
