/*
 * Copyright (c) 2026 MyLittleSuite
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'package:code_builder/code_builder.dart';
import 'package:dart_mapper/dart_mapper.dart';
import 'package:dart_mapper_generator/src/models/mapper/mapper_class.dart';
import 'package:dart_mapper_generator/src/processors/component_processor.dart';
import 'package:dart_mapper_generator/src/processors/mapper_processor.dart';
import 'package:test/test.dart';

void main() {
  group('MapperProcessor', () {
    test('omits timestamp docs by default', () {
      final generatedClass = _processMapper(timestampDoc: false);

      expect(
        generatedClass.accept(DartEmitter()).toString(),
        isNot(contains('Generated by DartMapperGenerator in date')),
      );
    });

    test('includes timestamp docs when globally enabled', () {
      final generatedClass = _processMapper(timestampDoc: true);

      expect(
        generatedClass.accept(DartEmitter()).toString(),
        contains('/// Generated by DartMapperGenerator in date'),
      );
    });
  });
}

Class _processMapper({required bool timestampDoc}) {
  return MapperProcessor(
    timestampDoc: timestampDoc,
    methodProcessor: const _UnusedMethodProcessor(),
  ).process(
    const ProcessorContext(
      mapperAnnotation: Mapper(),
      mapperClass: MapperClass(name: 'ExampleMapper'),
      importAliases: {},
    ),
  );
}

class _UnusedMethodProcessor extends ComponentProcessor<Method> {
  const _UnusedMethodProcessor();

  @override
  Method process(ProcessorContext context) {
    throw UnimplementedError();
  }
}
