// Golden test source for @Mapper(timestampDoc: ...) option.
//
// Validates that the generated implementation class includes or omits the
// "Generated by DartMapperGenerator in date ..." doc comment depending on the
// `timestampDoc` value set on the annotation.

import 'package:dart_mapper/dart_mapper.dart';
import 'package:source_gen_test/annotations.dart';

class TimestampSource {
  final String value;

  TimestampSource(this.value);
}

class TimestampTarget {
  final String value;

  TimestampTarget(this.value);
}

// ── Test 1: timestampDoc: true ─────────────────────────────────────────────
// The generated class should have the timestamp doc comment.

@ShouldGenerate(
  '/// Generated by DartMapperGenerator in date',
  contains: true,
)
@Mapper(timestampDoc: true)
abstract class TimestampOnMapper {
  TimestampTarget toTarget(TimestampSource source);
}

// ── Test 2: timestampDoc: false (explicit) ─────────────────────────────────
// The generated class should start directly with the class declaration.

@ShouldGenerate(
  r'''class TimestampOffMapperImpl extends TimestampOffMapper {''',
  contains: true,
)
@Mapper(timestampDoc: false)
abstract class TimestampOffMapper {
  TimestampTarget toTarget(TimestampSource source);
}

// ── Test 3: default (no timestampDoc set) ─────────────────────────────────
// The default is false, so the class should also start without a doc comment.

@ShouldGenerate(
  r'''class TimestampDefaultMapperImpl extends TimestampDefaultMapper {''',
  contains: true,
)
@Mapper()
abstract class TimestampDefaultMapper {
  TimestampTarget toTarget(TimestampSource source);
}
