// Golden test source for builder-level timestamp doc comments.

import 'package:dart_mapper/dart_mapper.dart';
import 'package:source_gen_test/annotations.dart';

class TimestampSource {
  final String value;

  TimestampSource(this.value);
}

class TimestampTarget {
  final String value;

  TimestampTarget(this.value);
}

@ShouldGenerate(
  '/// Generated by DartMapperGenerator in date',
  contains: true,
)
@ShouldGenerate(
  r'''class TimestampMapperImpl extends TimestampMapper {''',
  contains: true,
)
@Mapper()
abstract class TimestampMapper {
  TimestampTarget toTarget(TimestampSource source);
}
