name: Pipeline

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze ${{ matrix.working-directory }}
    strategy:
      matrix:
        working-directory:
          - example
          - packages/dart_mapper
          - packages/dart_mapper_generator
        include:
          - flutter: false
          - flutter: true
            working-directory: example
    uses: ./.github/workflows/analyze.yml
    with:
      working-directory: ${{ matrix.working-directory }}
      flutter: ${{ matrix.flutter }}

  test:
    name: Test ${{ matrix.working-directory }}
    strategy:
      matrix:
        working-directory:
          - packages/dart_mapper
          - packages/dart_mapper_generator
    uses: ./.github/workflows/test.yml
    with:
      working-directory: ${{ matrix.working-directory }}

  publish:
    name: Publish
    needs:
      - analyze
      - test
    uses: ./.github/workflows/publish.yml
