name: Publish

on:
  workflow_call:


jobs:
  dart_runner:
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/dart_mapper

  dart_mapper_generator:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - dart_runner
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/dart_mapper_generator
